:verbose: false
:concurrency: 10
:timeout: 25

:queues:
  - default
  - mailers

staging:
  :concurrency: 15
production:
  :concurrency: 25

:schedule:
  test_cron_job:
    cron: '0 */6 * * *' # every 6 hours
    class: TestCronJob
  end_expired_events:
    cron: "0 */1 * * *" # every hour
    class: EndExpiredEventsCronJob
